/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UsuarioDAOUser;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.UsuarioUser;

/**
 *
 * @author 98925
 */
public class JFrameCadastro extends javax.swing.JFrame {
    private int codigo = -1;
    /**
     * Creates new form JFrameCadatro
     */
    public JFrameCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelIcone = new javax.swing.JLabel();
        JLabelEmail = new javax.swing.JLabel();
        JLabelUsuario = new javax.swing.JLabel();
        JLabelSenha = new javax.swing.JLabel();
        JTextFieldEmail = new javax.swing.JTextField();
        JTextFieldUsuario = new javax.swing.JTextField();
        JButtonCadastrar = new javax.swing.JButton();
        JPasswordSenha = new javax.swing.JPasswordField();
        JLabelConfirmar = new javax.swing.JLabel();
        JPasswordConfirmar = new javax.swing.JPasswordField();
        JTextFieldNome = new javax.swing.JTextField();
        JLabelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        JLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/usuario.png"))); // NOI18N

        JLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelEmail.setText("E-Mail");

        JLabelUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelUsuario.setText("Usuario");

        JLabelSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelSenha.setText("Senha");

        JButtonCadastrar.setBackground(new java.awt.Color(122, 187, 255));
        JButtonCadastrar.setText("Cadastrar");
        JButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCadastrarActionPerformed(evt);
            }
        });

        JLabelConfirmar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLabelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelConfirmar.setText("Confirmar senha");

        JLabelNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNome.setText("Nome completo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(JTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelIcone)
                    .addComponent(JLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPasswordConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JLabelIcone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPasswordConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCadastrarActionPerformed
        if (JTextFieldNome.getText().trim().equals("")) {
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/Icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Algum usuário deve ser digitado!!!", "Aviso", JOptionPane.ERROR_MESSAGE, icone);
            return;
        }
        if (JTextFieldEmail.getText().trim().equals("")) {
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/Icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Algum email deve ser digitado!!!", "Aviso", JOptionPane.ERROR_MESSAGE, icone);
            return;
        }
        if (new String(JPasswordSenha.getPassword()).trim().equals("")) {
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/Icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Deve ser digitada alguma senha!!!", "Aviso", JOptionPane.ERROR_MESSAGE, icone);
            return;
        }
        if (new String(JPasswordConfirmar.getPassword()).trim().equals("")) {
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/Icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Deve ser confirmada a senha!!", "Aviso", JOptionPane.ERROR_MESSAGE, icone);
            return;
        } else {
            dispose();
            UsuarioUser user = new UsuarioUser();
            user.setNome(JTextFieldNome.getText());
            user.setUsuario(JTextFieldUsuario.getText());
            user.setSenha(new String(JPasswordConfirmar.getPassword()));
            user.setEmail(JTextFieldEmail.getText());
            user.setId(UsuarioDAOUser.inserir(user));
            codigo = user.getId();
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/Icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Usuário foi cadastrado!!!", "Aviso", JOptionPane.ERROR_MESSAGE, icone);
        }
    }//GEN-LAST:event_JButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCadastrar;
    private javax.swing.JLabel JLabelConfirmar;
    private javax.swing.JLabel JLabelEmail;
    private javax.swing.JLabel JLabelIcone;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelSenha;
    private javax.swing.JLabel JLabelUsuario;
    private javax.swing.JPasswordField JPasswordConfirmar;
    private javax.swing.JPasswordField JPasswordSenha;
    private javax.swing.JTextField JTextFieldEmail;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JTextField JTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
