/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MedicamentoDAO;
import dao.PaisDAO;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Medicamento;
import model.Pais;

/**
 *
 * @author Alice Sophia Koch
 * @author Allan Martins Da Silva
 * @author Mario Schwabe Filho
 *
 */
public class JFrameAlterarMedicamento extends javax.swing.JFrame {

    public Icon iconeAlerta = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
    public Icon iconeCerto = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/certo.png")));
    private int codigo = -1;

    /**
     * Creates new form JFrameAlterarMedicamentos
     */
    public JFrameAlterarMedicamento(int codigoParaAlterar) {
        this();
        this.codigo = codigoParaAlterar;
        Medicamento medicamento = MedicamentoDAO.buscarMedicamentoPorId(codigo);
        JTextFieldNome.setText(medicamento.getNome());
        selecionarPais(medicamento.getPais());
        JTextAreaContraindicacoes.setText(medicamento.getContraIndicacoes());
        JTextAreaPraQServe.setText(medicamento.getParaQServe());
        JTextAreaArmazenamento.setText(medicamento.getArmazenamento());
        JTextFieldPreco.setText(String.valueOf(medicamento.getPreco()));
    }

    public JFrameAlterarMedicamento() {
        initComponents();
        popularPais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaPraQServe = new javax.swing.JTextArea();
        JLabelPraQueServe = new javax.swing.JLabel();
        JLabelPreco = new javax.swing.JLabel();
        JTextFieldPreco = new javax.swing.JTextField();
        JLabelIcone = new javax.swing.JLabel();
        JLabelContraindicacoes = new javax.swing.JLabel();
        JLabelAlterar = new javax.swing.JLabel();
        JLabelNome = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTextAreaContraindicacoes = new javax.swing.JTextArea();
        JTextFieldNome = new javax.swing.JTextField();
        JLabelArmazenamento = new javax.swing.JLabel();
        JButtonCancelar = new javax.swing.JButton();
        JLabelPais = new javax.swing.JLabel();
        JButtonConcluir = new javax.swing.JButton();
        JComboBoxPais = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTextAreaArmazenamento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar medicamento");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        JTextAreaPraQServe.setColumns(20);
        JTextAreaPraQServe.setRows(5);
        jScrollPane1.setViewportView(JTextAreaPraQServe);
        JTextAreaPraQServe.setLineWrap(true);

        JLabelPraQueServe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPraQueServe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPraQueServe.setText("Para que serve");
        JLabelPraQueServe.setToolTipText("");

        JLabelPreco.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPreco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPreco.setText("Novo preço");

        JLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/medicamentoCadastro.png"))); // NOI18N

        JLabelContraindicacoes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelContraindicacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelContraindicacoes.setText("Contraindicações");

        JLabelAlterar.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        JLabelAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelAlterar.setText("Alterar Medicamento");

        JLabelNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNome.setText("Novo nome");

        JTextAreaContraindicacoes.setColumns(20);
        JTextAreaContraindicacoes.setRows(5);
        jScrollPane4.setViewportView(JTextAreaContraindicacoes);
        JTextAreaContraindicacoes.setLineWrap(true);

        JLabelArmazenamento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelArmazenamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelArmazenamento.setText("Armazenamento");

        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });

        JLabelPais.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPais.setText("Novo país");

        JButtonConcluir.setText("Concluir");
        JButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConcluirActionPerformed(evt);
            }
        });

        JTextAreaArmazenamento.setColumns(20);
        JTextAreaArmazenamento.setRows(5);
        jScrollPane2.setViewportView(JTextAreaArmazenamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(JLabelContraindicacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JLabelArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTextFieldPreco)
                                            .addComponent(JLabelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(203, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabelAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelPraQueServe, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLabelAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelPraQueServe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonCancelar)
                            .addComponent(JButtonConcluir))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelContraindicacoes)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConcluirActionPerformed
        if (JComboBoxPais.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algo em país!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextFieldNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em nome!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextFieldPreco.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em preço!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextAreaContraindicacoes.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em contraindicações!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextAreaPraQServe.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em armazentamento!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextAreaArmazenamento.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em armazenamento!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (codigo == -1) {
            Medicamento medicamento = new Medicamento();
            medicamento.setNome(JTextFieldNome.getText());
            medicamento.setPais((Pais) JComboBoxPais.getSelectedItem());
            medicamento.setParaQServe(JTextAreaPraQServe.getText());
            medicamento.setPreco(Float.parseFloat(JTextFieldPreco.getText()));
            medicamento.setArmazenamento(JTextAreaArmazenamento.getText());
            medicamento.setContraIndicacoes(JTextAreaContraindicacoes.getText());
            medicamento.setId(MedicamentoDAO.inserir(medicamento));
            codigo = medicamento.getId();
            JOptionPane.showMessageDialog(null, "Medicamento foi inserido!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeCerto);
        } else {
            Medicamento medicamento = new Medicamento();
            medicamento.setId(codigo);
            medicamento.setNome(JTextFieldNome.getText());
            medicamento.setPais((Pais) JComboBoxPais.getSelectedItem());
            medicamento.setParaQServe(JTextAreaPraQServe.getText());
            medicamento.setPreco(Float.parseFloat(JTextFieldPreco.getText()));
            medicamento.setArmazenamento(JTextAreaArmazenamento.getText());
            medicamento.setContraIndicacoes(JTextAreaContraindicacoes.getText());
            MedicamentoDAO.alterar(medicamento);
            JOptionPane.showMessageDialog(null, "Medicamento foi alterado!!!", "Aviso de Alteração de Medicamentos", JOptionPane.ERROR_MESSAGE, iconeCerto);
            dispose();
        }
    }//GEN-LAST:event_JButtonConcluirActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void popularPais() {
        ArrayList<Pais> paises = (ArrayList) PaisDAO.retornarPaisSemLimites();
        for (Pais pais : paises) {
            JComboBoxPais.addItem(pais);
        }
        JComboBoxPais.setSelectedIndex(-1);
    }

    private void selecionarPais(Pais paisParaSelecionar) {
        int quantidadeRegistros = JComboBoxPais.getItemCount();
        for (int i = 0; i < quantidadeRegistros; i++) {
            Pais pais = JComboBoxPais.getItemAt(i);
            if (pais.getNome().equals(paisParaSelecionar.getNome())) {
                JComboBoxPais.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonConcluir;
    private javax.swing.JComboBox<Pais> JComboBoxPais;
    private javax.swing.JLabel JLabelAlterar;
    private javax.swing.JLabel JLabelArmazenamento;
    private javax.swing.JLabel JLabelContraindicacoes;
    private javax.swing.JLabel JLabelIcone;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelPais;
    private javax.swing.JLabel JLabelPraQueServe;
    private javax.swing.JLabel JLabelPreco;
    private javax.swing.JTextArea JTextAreaArmazenamento;
    private javax.swing.JTextArea JTextAreaContraindicacoes;
    private javax.swing.JTextArea JTextAreaPraQServe;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JTextField JTextFieldPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
