package view;

import dao.CidadeDAO;
import dao.PaisDAO;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Cidade;
import model.Pais;

/**
 *
 * @author Alice Sophia Koch
 * @author Allan Martins Da Silva
 * @author Mario Schwabe Filho
 *
 */
public class JFrameAlterarCidade extends javax.swing.JFrame {

    public Icon iconeAlerta = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
    public Icon iconeCerto = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/certo.png")));

    private int codigo = -1;

    /**
     * Creates new form JFrameEditarCidade
     */
    public JFrameAlterarCidade(int codigoParaAlterar) {
        this();
        this.codigo = codigoParaAlterar;
        Cidade cidade = CidadeDAO.buscarCidadePorId(codigo);
        JTextFieldNome.setText(cidade.getNome());
        selecionarPais(cidade.getPais());
    }

    public JFrameAlterarCidade() {
        initComponents();
        popularPais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelCidade = new javax.swing.JLabel();
        JButtonCancelar = new javax.swing.JButton();
        JButtonAlterar = new javax.swing.JButton();
        JLabelAlterar = new javax.swing.JLabel();
        JComboBoxPais = new javax.swing.JComboBox<>();
        JLabelPais = new javax.swing.JLabel();
        JTextFieldNome = new javax.swing.JTextField();
        JLabelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar cidade");
        setResizable(false);

        JLabelCidade.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        JLabelCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCidade.setText("Alterar Cidade");

        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });

        JButtonAlterar.setText("Concluir");
        JButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterarActionPerformed(evt);
            }
        });

        JLabelAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cidadeAdicionar.png"))); // NOI18N
        JLabelAlterar.setToolTipText("");

        JLabelPais.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPais.setText("Novo país");

        JLabelNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNome.setText("Novo nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(JLabelAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextFieldNome)
                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(JLabelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonCancelar)
                    .addComponent(JButtonAlterar))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void JButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterarActionPerformed
        if (JComboBoxPais.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Algum país deve ser selecionado!!!");
            return;
        }
        if (JTextFieldNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Algum nome deve ser digitado!!!");
            return;
        }
        if (codigo == -1) {
            Cidade cidade = new Cidade();
            cidade.setNome(JTextFieldNome.getText());
            cidade.setPais((Pais) JComboBoxPais.getSelectedItem());
            cidade.setId(CidadeDAO.inserir(cidade));
            codigo = cidade.getId();
            JOptionPane.showMessageDialog(null, "Cidade foi inserida!!!");
        } else {
            Cidade cidade = new Cidade();
            cidade.setId(codigo);
            cidade.setNome(JTextFieldNome.getText());
            cidade.setPais((Pais) JComboBoxPais.getSelectedItem());
            CidadeDAO.alterar(cidade);
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/certo.png")));
            JOptionPane.showMessageDialog(null, "Cidade foi alterada!!!", "Aviso de Alteração de Cidades", JOptionPane.ERROR_MESSAGE, icone);
        }
        dispose();
    }//GEN-LAST:event_JButtonAlterarActionPerformed
    private void popularPais() {
        ArrayList<Pais> paises = (ArrayList) PaisDAO.retornarPaisSemLimites();
        for (Pais pais : paises) {
            JComboBoxPais.addItem(pais);
        }
        JComboBoxPais.setSelectedIndex(-1);
    }

    private void selecionarPais(Pais paisParaSelecionar) {
        int quantidadeRegistros = JComboBoxPais.getItemCount();
        for (int i = 0; i < quantidadeRegistros; i++) {
            Pais pais = JComboBoxPais.getItemAt(i);
            if (pais.getNome().equals(paisParaSelecionar.getNome())) {
                JComboBoxPais.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar;
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JComboBox<Pais> JComboBoxPais;
    private javax.swing.JLabel JLabelAlterar;
    private javax.swing.JLabel JLabelCidade;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelPais;
    private javax.swing.JTextField JTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
