/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UsuarioDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

/**
 *
 * @author Alice Sophia Koch
 */
public class JFrameGerenciamentoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGerenciamentoUsuarios
     */
    public JFrameGerenciamentoUsuarios() {
        initComponents();
        /*JFrameGerenciamentoUsuarios jframe = new JFrameGerenciamentoUsuarios();
        Color minhaCor = new Color(184, 242, 215);
        getContentPane().setBackground(minhaCor);
        jframe.getContentPane().setBackground(minhaCor);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane = new javax.swing.JScrollPane();
        TabelaUsuarios = new javax.swing.JTable();
        JButtonExcluir = new javax.swing.JButton();
        JButtonEditar = new javax.swing.JButton();
        JButtonAdicionar = new javax.swing.JButton();
        JButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Usuários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Usuário", "Email", "Senha Criptografada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaUsuarios.getTableHeader().setReorderingAllowed(false);
        JScrollPane.setViewportView(TabelaUsuarios);
        if (TabelaUsuarios.getColumnModel().getColumnCount() > 0) {
            TabelaUsuarios.getColumnModel().getColumn(0).setMinWidth(75);
            TabelaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(75);
            TabelaUsuarios.getColumnModel().getColumn(0).setMaxWidth(75);
            TabelaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            TabelaUsuarios.getColumnModel().getColumn(2).setResizable(false);
            TabelaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
            TabelaUsuarios.getColumnModel().getColumn(3).setResizable(false);
            TabelaUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
        TabelaUsuarios.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);

        JButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        JButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonExcluirActionPerformed(evt);
            }
        });

        JButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        JButtonEditar.setToolTipText("");
        JButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditarActionPerformed(evt);
            }
        });

        JButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar.png"))); // NOI18N
        JButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAdicionarActionPerformed(evt);
            }
        });

        JButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        JButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(JScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonVoltarActionPerformed

    private void JButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAdicionarActionPerformed
        JFrameCadastroUsuario user = new JFrameCadastroUsuario();
        user.setVisible(true);
    }//GEN-LAST:event_JButtonAdicionarActionPerformed

    private void JButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditarActionPerformed
        if (TabelaUsuarios.getSelectedRow() > -1) {
            int linhaSelecionada = TabelaUsuarios.getSelectedRow();
            int codigoParaAlterar = Integer.parseInt(TabelaUsuarios.getValueAt(linhaSelecionada, 0).toString());
            JFrameAlterarUsuario alterar = new JFrameAlterarUsuario(codigoParaAlterar);
            alterar.setVisible(true);
        } else {
            Icon icone = new ImageIcon (getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Não foi selecionado nenhum item na tabela","Aviso",JOptionPane.ERROR_MESSAGE,icone);
        }
    }//GEN-LAST:event_JButtonEditarActionPerformed

    private void JButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonExcluirActionPerformed
        if (TabelaUsuarios.getSelectedRow() > -1) {
            int linhaSelecionada = TabelaUsuarios.getSelectedRow();
            int codigoParaExcluir = Integer.parseInt(TabelaUsuarios.getValueAt(linhaSelecionada, 0).toString());
            DefaultTableModel dtm = (DefaultTableModel) TabelaUsuarios.getModel();
            UsuarioDAO.excluir(codigoParaExcluir);
            dtm.removeRow(linhaSelecionada);
        } else {
            Icon icone = new ImageIcon (getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Não foi selecionado nenhum item da tabela","Aviso",JOptionPane.ERROR_MESSAGE,icone);
        }
    }//GEN-LAST:event_JButtonExcluirActionPerformed
    private int u = 0;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarDados();
    }//GEN-LAST:event_formWindowActivated

    private void listarDados() {
        ArrayList<Usuario> users = (ArrayList<Usuario>) UsuarioDAO.retornarUsuario();
        DefaultTableModel dtm = (DefaultTableModel) TabelaUsuarios.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < users.size(); i++) {
            Usuario user = users.get(i);
            dtm.addRow(new Object[]{
                user.getId(),
                user.getNome(),
                user.getUsuario(),
                user.getEmail(),
                user.getSenha()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGerenciamentoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGerenciamentoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGerenciamentoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGerenciamentoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGerenciamentoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAdicionar;
    private javax.swing.JButton JButtonEditar;
    private javax.swing.JButton JButtonExcluir;
    private javax.swing.JButton JButtonVoltar;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JTable TabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
