/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MedicamentoDAO;
import dao.MedicamentoInternacionalDAO;
import dao.PaisDAO;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Medicamento;
import model.Pais;

/**
 *
 * @author Mario Schwabe Filho
 * @author Alice Sophia Koch
 * @author Allan Martins Da Silva
 *
 */
public class JFrameCadastroMedicamentoInternacional extends javax.swing.JFrame {

    public Icon iconeAlerta  = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
    public Icon iconeCerto = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/certo.png")));

    /**
     * Creates new form JFrameCadastroMedicamento
     */
    public JFrameCadastroMedicamentoInternacional() {
        initComponents();
    }

    public void popularPaises() {
        ArrayList<Pais> paises = (ArrayList) PaisDAO.retornarPaisSemLimites();
        for (Pais pais : paises) {
            jComboBoxPaisOrigem.addItem(pais);
            jComboBoxPaisDestino.addItem(pais);
        }
        jComboBoxPaisOrigem.setSelectedIndex(-1);
        jComboBoxPaisDestino.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        JButtonCancelar = new javax.swing.JButton();
        JButtonConcluir = new javax.swing.JButton();
        JLabelIcone = new javax.swing.JLabel();
        JLabelCadastro = new javax.swing.JLabel();
        JLabelMedicamentoOrigem = new javax.swing.JLabel();
        JLabelPaisOrigem = new javax.swing.JLabel();
        JLabelMedicamentoDestino = new javax.swing.JLabel();
        JLabelPaisDestino = new javax.swing.JLabel();
        jComboBoxPaisOrigem = new javax.swing.JComboBox<>();
        jComboBoxMedicamentoOrigem = new javax.swing.JComboBox<>();
        jComboBoxPaisDestino = new javax.swing.JComboBox<>();
        JComboBoxMedicamentoDestino = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de medicamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });

        JButtonConcluir.setText("Concluir");
        JButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConcluirActionPerformed(evt);
            }
        });

        JLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/medicamentoCadastro.png"))); // NOI18N

        JLabelCadastro.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        JLabelCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCadastro.setText("Cadastrar Medicamento Internacional");

        JLabelMedicamentoOrigem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelMedicamentoOrigem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelMedicamentoOrigem.setText("Medicamento Origem");

        JLabelPaisOrigem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPaisOrigem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPaisOrigem.setText("Pais Origem");

        JLabelMedicamentoDestino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelMedicamentoDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelMedicamentoDestino.setText("Medicamento Destino");

        JLabelPaisDestino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPaisDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPaisDestino.setText("Pais Destino");

        jComboBoxPaisOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPaisOrigemItemStateChanged(evt);
            }
        });

        jComboBoxPaisDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPaisDestinoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(JLabelIcone)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelMedicamentoOrigem)
                                    .addComponent(jComboBoxMedicamentoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(284, 284, 284)
                                            .addComponent(JLabelPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jComboBoxPaisOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JLabelMedicamentoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JComboBoxMedicamentoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JLabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(JLabelCadastro)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelMedicamentoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelMedicamentoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JLabelIcone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMedicamentoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBoxMedicamentoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonConcluir)
                    .addComponent(JButtonCancelar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        popularPaises();
    }//GEN-LAST:event_formWindowActivated

    private void JButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConcluirActionPerformed
        if (jComboBoxPaisOrigem.getSelectedIndex() == -1) {
            Icon icone = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algum pais de origem!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (jComboBoxPaisDestino.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algum pais de destino!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (jComboBoxMedicamentoOrigem.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algum medicamento de origem!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JComboBoxMedicamentoDestino.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algum medicamento de destino!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        } else {
            Medicamento medicamentoOrigem = (Medicamento) jComboBoxMedicamentoOrigem.getSelectedItem();
            Medicamento medicamentoDestino = (Medicamento) JComboBoxMedicamentoDestino.getSelectedItem();
            int valor = MedicamentoInternacionalDAO.inserir(medicamentoOrigem, medicamentoDestino);
            JOptionPane.showMessageDialog(null, "Medicamento foi inserido!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeCerto);
            dispose();
        }
    }//GEN-LAST:event_JButtonConcluirActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void jComboBoxPaisOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPaisOrigemItemStateChanged
        Pais paisOrigem = (Pais) jComboBoxPaisOrigem.getSelectedItem();
        if (paisOrigem != null) {
            ArrayList<Medicamento> medicamentos = (ArrayList) MedicamentoDAO.listarMedicamentos(paisOrigem.getId());
            jComboBoxMedicamentoOrigem.removeAllItems();
            for (Medicamento medicamento : medicamentos) {
                jComboBoxMedicamentoOrigem.addItem(medicamento);
            }
            jComboBoxMedicamentoOrigem.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jComboBoxPaisOrigemItemStateChanged

    private void jComboBoxPaisDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPaisDestinoItemStateChanged
        Pais paisDestino = (Pais) jComboBoxPaisDestino.getSelectedItem();
        if (paisDestino != null) {
            ArrayList<Medicamento> medicamentos = (ArrayList) MedicamentoDAO.listarMedicamentos(paisDestino.getId());
            JComboBoxMedicamentoDestino.removeAllItems();
            for (Medicamento medicamento : medicamentos) {
                JComboBoxMedicamentoDestino.addItem(medicamento);
            }
            JComboBoxMedicamentoDestino.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jComboBoxPaisDestinoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamentoInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamentoInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamentoInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamentoInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroMedicamentoInternacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonConcluir;
    private javax.swing.JComboBox<Medicamento> JComboBoxMedicamentoDestino;
    private javax.swing.JLabel JLabelCadastro;
    private javax.swing.JLabel JLabelIcone;
    private javax.swing.JLabel JLabelMedicamentoDestino;
    private javax.swing.JLabel JLabelMedicamentoOrigem;
    private javax.swing.JLabel JLabelPaisDestino;
    private javax.swing.JLabel JLabelPaisOrigem;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<Medicamento> jComboBoxMedicamentoOrigem;
    private javax.swing.JComboBox<Pais> jComboBoxPaisDestino;
    private javax.swing.JComboBox<Pais> jComboBoxPaisOrigem;
    // End of variables declaration//GEN-END:variables
}
