/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AdministradorDAO;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import model.Administrador;
import javax.swing.ImageIcon;

/**
 *
 * @author Alice Sophia Koch
 */
public class JFrameAlterarAdmin extends javax.swing.JFrame {
    private int codigo = -1;
    /**
     * Creates new form JFrameAlterarAdmin
     */
    
    public JFrameAlterarAdmin(int codigoParaAlterar) {
        this();
        this.codigo = codigoParaAlterar;
        Administrador admin = AdministradorDAO.buscarAdminPorId(codigo);
        JTextFieldNome.setText(admin.getNome());
        JTextFieldUsuario.setText(admin.getUsuario());
        //JPasswordSenha.setText(admin.getSenha());
    }
        
    public JFrameAlterarAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextFieldNome = new javax.swing.JTextField();
        JLabelUsuario = new javax.swing.JLabel();
        JButtonCancelar = new javax.swing.JButton();
        JTextFieldUsuario = new javax.swing.JTextField();
        JButtonConcluir = new javax.swing.JButton();
        JLabelSenha = new javax.swing.JLabel();
        JLabelAlterar = new javax.swing.JLabel();
        JPasswordSenha = new javax.swing.JPasswordField();
        JLabelIcone = new javax.swing.JLabel();
        JLabelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar administrador");
        setResizable(false);

        JLabelUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelUsuario.setText("Novo usuário");

        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });

        JButtonConcluir.setText("Concluir");
        JButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConcluirActionPerformed(evt);
            }
        });

        JLabelSenha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelSenha.setText("Nova senha");

        JLabelAlterar.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        JLabelAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelAlterar.setText("Alterar Administrador");
        JLabelAlterar.setToolTipText("");

        JLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adminCadastro.png"))); // NOI18N

        JLabelNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNome.setText("Novo nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelAlterar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonCancelar)
                            .addComponent(JButtonConcluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void JButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConcluirActionPerformed
        if (JTextFieldNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Algum nome deve ser digitado!!!");
            return;
        }
        if (JTextFieldUsuario.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Deve ser digitado um nome de usuário!!!");
            return;
        }
        if (new String(JPasswordSenha.getPassword()).trim().equals("")){
            JOptionPane.showMessageDialog(null, "Deve ser digitada alguma senha!!!");
            return;
        }
        if (codigo == -1) {
            Administrador admin = new Administrador();
            admin.setNome(JTextFieldNome.getText());
            admin.setUsuario(JTextFieldUsuario.getText());
            admin.setSenha(new String(JPasswordSenha.getPassword()));
            admin.setId(AdministradorDAO.inserir(admin));
            codigo = admin.getId();
            JOptionPane.showMessageDialog(null, "Administrador foi inserido!!!");
        }else{
            Administrador admin = new Administrador();
            admin.setId(codigo);
            admin.setNome(JTextFieldNome.getText());
            admin.setUsuario(JTextFieldUsuario.getText());
            admin.setSenha(new String(JPasswordSenha.getPassword()));
            AdministradorDAO.alterar(admin);
            Icon icone = new ImageIcon (getToolkit().createImage(getClass().getResource("/icones/certo.png")));
            JOptionPane.showMessageDialog(null, "Administrador foi alterado!!!","Aviso de Alteração de ADM",JOptionPane.ERROR_MESSAGE,icone);
        }
        dispose();
    }//GEN-LAST:event_JButtonConcluirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonConcluir;
    private javax.swing.JLabel JLabelAlterar;
    private javax.swing.JLabel JLabelIcone;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelSenha;
    private javax.swing.JLabel JLabelUsuario;
    private javax.swing.JPasswordField JPasswordSenha;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JTextField JTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
