/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MedicamentoDAO;
import dao.PaisDAO;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Medicamento;
import model.Pais;

/**
 *
 * @author Alice Sophia Koch
 * @author Allan Martins Da Silva
 * @author Mario Schwabe Filho
 *
 */
public class JFrameCadastroMedicamento extends javax.swing.JFrame {

    public Icon iconeAlerta = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/alerta.png")));
    public Icon iconeCerto = new ImageIcon(getToolkit().createImage(getClass().getResource("/icones/certo.png")));

    /**
     * Creates new form JFrameCadastroMedicamento
     */
    public JFrameCadastroMedicamento() {
        initComponents();
    }

    public void popularPaises() {
        ArrayList<Pais> paises = (ArrayList) PaisDAO.retornarPaisSemLimites();
        for (Pais pais : paises) {
            JComboBoxPais.addItem(pais);
        }
        JComboBoxPais.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        JButtonCancelar = new javax.swing.JButton();
        JButtonConcluir = new javax.swing.JButton();
        JLabelIcone = new javax.swing.JLabel();
        JLabelCadastro = new javax.swing.JLabel();
        JLabelNome = new javax.swing.JLabel();
        JTextFieldNome = new javax.swing.JTextField();
        JLabelPais = new javax.swing.JLabel();
        JComboBoxPais = new javax.swing.JComboBox<>();
        JLabelPraQueServe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaContraIndicacoes = new javax.swing.JTextArea();
        JLabelContraindicacoes = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTextAreaPraQServe = new javax.swing.JTextArea();
        JLabelArmazenamento = new javax.swing.JLabel();
        JLabelPreco = new javax.swing.JLabel();
        JTextFieldPreco = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaArmazenamento = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de medicamento");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });

        JButtonConcluir.setText("Concluir");
        JButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConcluirActionPerformed(evt);
            }
        });

        JLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/medicamentoCadastro.png"))); // NOI18N

        JLabelCadastro.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        JLabelCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCadastro.setText("Cadastrar Medicamento");

        JLabelNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNome.setText("Nome");

        JLabelPais.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPais.setText("País");

        JLabelPraQueServe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPraQueServe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPraQueServe.setText("Para que serve");
        JLabelPraQueServe.setToolTipText("");

        JTextAreaContraIndicacoes.setColumns(20);
        JTextAreaContraIndicacoes.setRows(5);
        jScrollPane1.setViewportView(JTextAreaContraIndicacoes);

        JLabelContraindicacoes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelContraindicacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelContraindicacoes.setText("Contraindicações");

        JTextAreaPraQServe.setColumns(20);
        JTextAreaPraQServe.setRows(5);
        jScrollPane4.setViewportView(JTextAreaPraQServe);

        JLabelArmazenamento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelArmazenamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelArmazenamento.setText("Armazenamento");

        JLabelPreco.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JLabelPreco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPreco.setText("Preço");

        jTextAreaArmazenamento.setColumns(20);
        jTextAreaArmazenamento.setRows(5);
        jScrollPane7.setViewportView(jTextAreaArmazenamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLabelContraindicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabelPraQueServe, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(JTextFieldPreco)
                            .addComponent(JLabelArmazenamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(572, 572, 572)
                        .addComponent(JButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(JLabelCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(JLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelPraQueServe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelContraindicacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(JLabelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonCancelar)
                    .addComponent(JButtonConcluir))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConcluirActionPerformed
        if (JComboBoxPais.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Deve ser selecionado algum pais!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextFieldNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em nome!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (jTextAreaArmazenamento.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em armazenamento!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextAreaContraIndicacoes.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em contra indicações!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        }
        if (JTextFieldPreco.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve ser digitado algo em preço!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeAlerta);
            return;
        } else {
            Medicamento medicamento = new Medicamento();
            medicamento.setNome(JTextFieldNome.getText());
            medicamento.setPais((Pais) (JComboBoxPais.getSelectedItem()));
            medicamento.setParaQServe(JTextAreaContraIndicacoes.getText());
            medicamento.setPreco(Float.parseFloat(JTextFieldPreco.getText()));
            medicamento.setContraIndicacoes(JTextAreaPraQServe.getText());
            medicamento.setArmazenamento(jTextAreaArmazenamento.getText());
            medicamento.setId(MedicamentoDAO.inserir(medicamento));
            JOptionPane.showMessageDialog(null, "Medicamento foi cadastrado com sucesso!!!", "Aviso", JOptionPane.ERROR_MESSAGE, iconeCerto);
            dispose();
        }
    }//GEN-LAST:event_JButtonConcluirActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        popularPaises();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonConcluir;
    private javax.swing.JComboBox<Pais> JComboBoxPais;
    private javax.swing.JLabel JLabelArmazenamento;
    private javax.swing.JLabel JLabelCadastro;
    private javax.swing.JLabel JLabelContraindicacoes;
    private javax.swing.JLabel JLabelIcone;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelPais;
    private javax.swing.JLabel JLabelPraQueServe;
    private javax.swing.JLabel JLabelPreco;
    private javax.swing.JTextArea JTextAreaContraIndicacoes;
    private javax.swing.JTextArea JTextAreaPraQServe;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JTextField JTextFieldPreco;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextAreaArmazenamento;
    // End of variables declaration//GEN-END:variables
}
